JakduK/jakduk-api

- README.md
- README_KO.md
- WebContent/WEB-INF/views/about/about-us-en.jsp
> translation

- jakduk-common/src/com/jakduk/service/EmailService.java
- jakduk-web/WebContent/WEB-INF/views/board/freeEdit.jsp
- jakduk-web/WebContent/WEB-INF/views/board/freePosts.jsp
- jakduk-web/WebContent/WEB-INF/views/board/freeView.jsp
- jakduk-web/WebContent/WEB-INF/views/board/freeWrite.jsp
- jakduk-web/WebContent/WEB-INF/views/home/home.jsp
- jakduk-web/resources/messages/common_en.properties
- jakduk-web/resources/messages/common_ko.properties
- jakduk-web/src/com/jakduk/controller/AccessController.java
> Improve ux

- jakduk-web/WebContent/WEB-INF/views/board/freeEdit.jsp
- jakduk-web/WebContent/WEB-INF/views/board/freeWrite.jsp
- jakduk-web/bower.json
> Fixes bugs

- jakduk-web/WebContent/WEB-INF/views/jakdu/scheduleView.jsp
- jakduk-web/WebContent/resources/jakduk/css/jakduk.css
> 작두타기 키패드ui 완성

- jakduk-web/pom.xml
- pom.xml
> Maven execute external program

- jakduk-web/WebContent/WEB-INF/views/stats/attendanceLeague.jsp
- jakduk-web/WebContent/WEB-INF/wro.xml
> fix wro4j 사이드이펙트

- jakduk-web/WebContent/WEB-INF/views/access/passwordFind.jsp
- jakduk-web/WebContent/WEB-INF/views/access/passwordReset.jsp
- jakduk-web/WebContent/WEB-INF/views/user/profileUpdate.jsp
- jakduk-web/WebContent/WEB-INF/views/user/socialProfileUpdate.jsp
- jakduk-web/WebContent/WEB-INF/views/user/socialWrite.jsp
- jakduk-web/WebContent/WEB-INF/views/user/write.jsp
> ngModel은 valid상태일때 업데이트되기 때문에 form validation을 ngChange로 하면 안됨.

- jakduk-web/WebContent/WEB-INF/views/include/html-header.jsp
- jakduk-web/WebContent/resources/jakduk/js/jakduk.js
- google analytics 사용자 설정 누락
수정이 늦어서 죄송... 개인사정으로 일이 많았습니다. :bow:
> wro4j 오류 수정

- jakduk-web/src/main/webapp/resources/jakduk/js/admin.js
- jakduk-web/src/main/webapp/resources/jakduk/template/admin-data-view.html
- jakduk-web/src/main/webapp/resources/jakduk/template/admin-write-board-category.html
> Get Attendance League 나오도록

- jakduk-web/src/main/webapp/resources/jakduk/js/admin.js
- jakduk-web/src/main/webapp/resources/jakduk/template/admin-data-view.html
> Get Attendance League

- jakduk-web/src/main/java/com/jakduk/restcontroller/BoardRestController.java
> 게시물 목록api 구현

- jakduk-common/src/main/java/com/jakduk/service/GalleryService.java
- jakduk-web/src/main/java/com/jakduk/controller/GalleryController.java
- jakduk-web/src/main/java/com/jakduk/restcontroller/gallery/GalleryRestController.java
- jakduk-web/src/main/java/com/jakduk/restcontroller/gallery/vo/GalleryResponse.java
get: /gallery/{id}
post: /gallery/{id}/{feeling}
> 갤러리 api 추가

- build.gradle
- jakduk-api/src/main/java/com/jakduk/api/restcontroller/board/BoardRestController.java
- jakduk-api/src/main/java/com/jakduk/api/restcontroller/board/vo/FreeCommentsOnList.java
- jakduk-api/src/main/java/com/jakduk/api/restcontroller/gallery/GalleryRestController.java
- jakduk-core/src/main/java/com/jakduk/core/model/db/BoardFreeComment.java
- jakduk-core/src/main/java/com/jakduk/core/model/embedded/BoardItem.java
- jakduk-core/src/main/java/com/jakduk/core/model/embedded/BoardStatus.java
- jakduk-core/src/main/java/com/jakduk/core/model/simple/BoardFreeOnSearchComment.java
- jakduk-core/src/main/java/com/jakduk/core/service/BoardFreeService.java
- jakduk-core/src/main/java/com/jakduk/core/service/GalleryService.java
> 최신 댓글 목록의 BoardItem에 status 추가

- core/src/main/resources/application-core-default.yml
> rabbitMQ의 검색어 인덱싱 routingKey의 값 오타 변경

- src/main/asciidoc/jakduk-api.adoc
- src/main/java/com/jakduk/api/common/Constants.java
- src/main/java/com/jakduk/api/common/rabbitmq/ElasticsearchRoutingKey.java
- src/main/java/com/jakduk/api/common/rabbitmq/RabbitMQPublisher.java
- src/main/java/com/jakduk/api/listener/ElasticsearchListener.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsArticle.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsArticleSource.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsCommentSource.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsGallerySource.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsParentArticle.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsSearchWord.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsTermsBucket.java
- src/main/java/com/jakduk/api/restcontroller/SearchRestController.java
- src/main/java/com/jakduk/api/restcontroller/vo/search/ArticleSource.java
- src/main/java/com/jakduk/api/restcontroller/vo/search/SearchArticleResult.java
- src/main/java/com/jakduk/api/restcontroller/vo/search/SearchBoardResult.java
- src/main/java/com/jakduk/api/restcontroller/vo/search/SearchUnifiedResponse.java
- src/main/java/com/jakduk/api/service/ArticleService.java
- src/main/java/com/jakduk/api/service/SearchService.java
- src/main/resources/application-default.yml
- src/main/resources/application-dev.yml
- src/main/resources/application-production.yml
- src/test/java/com/jakduk/api/board/ArticleMvcTests.java
- src/test/java/com/jakduk/api/common/RabbitMQRoutingKeyTest.java
- src/test/java/com/jakduk/api/rabbitmq/RabbitMQPublisherTest.java
- src/test/java/com/jakduk/api/search/SearchMvcTests.java
- src/test/java/com/jakduk/api/search/SearchServiceTest.java
몽고 DB collection 형태가 바뀌면서, ES도 함께 바뀌어야 합니다.
- 찾기 API 수정
- 각종 필드이름 변경
- doc 추가
> Issue 291/fix search

- src/main/java/com/jakduk/api/common/Constants.java
- src/main/java/com/jakduk/api/common/util/AuthUtils.java
- src/main/java/com/jakduk/api/model/embedded/GalleryStatus.java
- src/main/java/com/jakduk/api/restcontroller/BoardRestController.java
- src/main/java/com/jakduk/api/service/ArticleService.java
- src/main/java/com/jakduk/api/service/GalleryService.java
- src/test/java/com/jakduk/api/auth/AuthMvcTests.java
- src/test/java/com/jakduk/api/auth/TestMvcConfig.java
- src/test/java/com/jakduk/api/auth/WithMockJakdukUser.java
- src/test/java/com/jakduk/api/auth/WithMockJakdukUserSecurityContextFactory.java
- src/test/java/com/jakduk/api/board/ArticleCommentMvcTests.java
- src/test/java/com/jakduk/api/board/ArticleMvcTests.java
- src/test/java/com/jakduk/api/search/SearchMvcTests.java
> Revert "#293 글쓰기&글고치기 시 그림 이름 안 바뀌는 현상"

- build.gradle
- src/main/java/com/jakduk/api/common/rabbitmq/RabbitMQPublisher.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsArticle.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsArticleSource.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsComment.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsCommentSource.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsGallery.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsGallerySource.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsJakduComment.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsParentArticle.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsSearchWord.java
- src/main/java/com/jakduk/api/model/elasticsearch/EsTermsBucket.java
- src/main/java/com/jakduk/api/model/rabbitmq/EmailPayload.java
- src/main/java/com/jakduk/api/service/SearchService.java
- src/test/java/com/jakduk/api/notification/NotificationTest.java
- src/test/java/com/jakduk/api/rabbitmq/RabbitMQPublisherTest.java
- src/test/java/com/jakduk/api/search/SearchMvcTests.java
ES 객체만 lombok 애너테이션 없앴는데, 양이 너무 많다
> #328 lombok fadeout

- src/test/java/com/jakduk/api/mock/WithMockAdminUserSecurityContextFactory.java
> #348 JUint 코드 수정

- src/main/java/com/jakduk/api/common/util/AuthUtils.java
- src/main/java/com/jakduk/api/configuration/security/SecurityConfig.java
is_email_verified -> has_email
JsonNode 프로퍼티를 메소드 체이닝으로 참조할땐 NPE 예방을 위해 path 메소드를 사용 해야한다.
> 카카오 JSON 스펙 오류 수정

- build.gradle
- src/main/java/com/jakduk/api/service/SearchService.java
- src/main/resources/application-default.yml
- src/main/resources/application-dev.yml
> Issue 352/elasticsearch indexing not working

- README.md
- src/main/java/com/jakduk/api/common/util/JakdukUtils.java
html태그 삭제 방식 교체 jsoup -> regex
텔레그램 초대 링크 삭제
> fixed #357

- src/main/resources/application-default.yml
- src/main/resources/application-dev.yml
* jakduk-stotage path 고침
* logging.file 안되는 현상 고침
> dev profile 정상화
